wpilibsuite/PathWeaver

src/main/java/edu/wpi/first/pathui/PathDisplayController.java
src/main/resources/edu/wpi/first/pathui/main.fxml
src/main/resources/edu/wpi/first/pathui/pathDisplay.fxml

Corrected deleting the wrong items when editing a path

---

pmd-ruleset.xml
src/main/java/edu/wpi/first/pathui/PathDisplayController.java
src/main/resources/edu/wpi/first/pathui/pathDisplay.fxml

Sort splines vectors and waypoints into own group to handle z ordering

---

src/main/java/edu/wpi/first/pathui/MainController.java

Display path if selected in auton menu

---

src/main/java/edu/wpi/first/pathui/MainIOUtil.java
src/main/java/edu/wpi/first/pathui/PathDisplayController.java
src/main/java/edu/wpi/first/pathui/Waypoint.java

Only shows a single paths vector at a time. This is set alongside selectedWaypoint.
Fixes #35

Hide all vectors on paths not currently being worked with

---

src/main/java/edu/wpi/first/pathui/DragHandler.java
src/main/java/edu/wpi/first/pathui/PathDisplayController.java

Create DragHandler class that handles all the dragging for a PathDisplayController. Add shift-drag on waypoint that moves entire path while checking bounds on all waypoints.
Fixes #49.

Add Shift-drag to move entire path

---

src/main/java/edu/wpi/first/pathui/DragHandler.java
src/main/java/edu/wpi/first/pathui/PathDisplayController.java
src/main/java/edu/wpi/first/pathui/Waypoint.java

Also fixed stack overflow exception from updates triggering too much.
Fixes #56

Removed null pointer exception related to setting currentWaypoint to nul

---

src/main/java/edu/wpi/first/pathui/MainController.java
src/main/java/edu/wpi/first/pathui/PathCell.java
src/main/java/edu/wpi/first/pathui/Waypoint.java

Allow paths within auton to be reordered by dragging paths around

---

src/main/java/edu/wpi/first/pathui/Path.java
src/main/java/edu/wpi/first/pathui/PathDisplayController.java

Check validity of flipped points

---

src/main/java/edu/wpi/first/pathui/DragHandler.java

Drag Targets accept drags if target is valid

---

src/main/java/edu/wpi/first/pathui/MainController.java
src/main/java/edu/wpi/first/pathui/MainIOUtil.java
src/main/java/edu/wpi/first/pathui/Path.java
src/main/java/edu/wpi/first/pathui/PathDisplayController.java
src/main/resources/edu/wpi/first/pathui/main.fxml

Add ability to duplicate selected path.

---

src/main/java/edu/wpi/first/pathweaver/MainController.java
src/main/java/edu/wpi/first/pathweaver/PathDisplayController.java

Fix NPE when duplicating or flipping path

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Upgrade to gradle 4.9

---

src/main/java/edu/wpi/first/pathweaver/MainController.java
src/main/java/edu/wpi/first/pathweaver/PathCell.java

Fix issue where auton with no paths showed paths

---

src/main/java/edu/wpi/first/pathweaver/CreateProjectController.java
src/main/java/edu/wpi/first/pathweaver/DragHandler.java
src/main/java/edu/wpi/first/pathweaver/EditWaypointController.java
src/main/java/edu/wpi/first/pathweaver/FxUtils.java
src/main/java/edu/wpi/first/pathweaver/MainController.java
src/main/java/edu/wpi/first/pathweaver/Path.java
src/main/java/edu/wpi/first/pathweaver/PathDisplayController.java
src/main/java/edu/wpi/first/pathweaver/PathIOUtil.java
src/main/java/edu/wpi/first/pathweaver/ProgramPreferences.java
src/main/java/edu/wpi/first/pathweaver/ProjectPreferences.java
src/main/java/edu/wpi/first/pathweaver/Waypoint.java
src/main/java/edu/wpi/first/pathweaver/WelcomeController.java
src/main/resources/edu/wpi/first/pathweaver/editWaypoint.fxml
src/main/resources/edu/wpi/first/pathweaver/main.fxml
src/main/resources/edu/wpi/first/pathweaver/style.css

Adds a pane below the field to edit a waypoint (X, Y, Tangent X, Tangent Y, Locked Tangent, Name). Closes #83 and closes #69.

Add pane for editing waypoint and setting name

---

build.gradle.kts
src/main/java/edu/wpi/first/pathweaver/FxUtils.java
src/main/java/edu/wpi/first/pathweaver/MainController.java

Adds "-Xlint:unchecked" and "-Xlint:deprecation" and corrects associated issues.

Add Java unchecked and deprecation warnings

---

build.gradle.kts

The v in it is odd, and should not be a version being used

Fix version if no git tag found

---

azure-pipelines.yml

Turn off mac tests so builds work again until issue is resolved

Fix Mac build

---

src/main/java/edu/wpi/first/hal/HAL.java

Fixes #157.
Needs testing (and a unit test).

Add dummy HAL module to handle usage reporting

---

src/main/java/edu/wpi/first/pathweaver/PathWeaver.java

Fix linux size issue

---

src/main/java/edu/wpi/first/pathweaver/spline/wpilib/WpilibSpline.java

Co-Authored-By: carbotaniuman <41451839+carbotaniuman@users.noreply.github.com>

Fix path used for JSON export

---

src/main/java/edu/wpi/first/pathweaver/Waypoint.java

Fix waypoint arrow rotation

---

README.md
src/main/java/edu/wpi/first/pathweaver/WelcomeController.java

Use frc-docs link to Pathweaver documentation

---

README.md
src/main/java/edu/wpi/first/pathweaver/WelcomeController.java

Fix link to documentation

---

src/main/java/edu/wpi/first/pathweaver/spline/wpilib/WpilibSpline.java

Fixes undefined class exception in #165, but not the underlying cause for the failure.

Set error handler for TrajectoryGenerator

---

src/main/java/edu/wpi/first/pathweaver/EditWaypointController.java
src/main/java/edu/wpi/first/pathweaver/PathIOUtil.java
src/main/java/edu/wpi/first/pathweaver/Waypoint.java
src/main/java/edu/wpi/first/pathweaver/path/Path.java
src/main/java/edu/wpi/first/pathweaver/path/wpilib/WpilibPath.java
src/main/java/edu/wpi/first/pathweaver/spline/wpilib/WpilibSpline.java
src/main/resources/edu/wpi/first/pathweaver/editWaypoint.fxml

resolves #176 
Adds the ability to plot reverse splines (where the robot drives backwards)
These are indicated by a dashed line and can be toggled using the right click menu on the waypoints.

Reversed splines

---

src/main/java/edu/wpi/first/pathweaver/spline/wpilib/WpilibSpline.java

Make PathWeaver JSON export match WPILib coordinates

---

src/main/java/edu/wpi/first/pathweaver/spline/wpilib/WpilibSpline.java

Fix export units

---

src/main/java/edu/wpi/first/pathweaver/MainController.java

It previously just said "Message".

Give alert for successful export a more useful message

---

dependencies.gradle
src/main/java/edu/wpi/first/pathweaver/PathWeaver.java

Required for https://github.com/wpilibsuite/allwpilib/pull/3257

Extract wpimathjni and wpiutiljni

---

src/main/java/edu/wpi/first/pathweaver/CreateProjectController.java
src/main/java/edu/wpi/first/pathweaver/ProjectPreferences.java

Otherwise you have to completely exit the program and start it again

Added an option to go back to the Welcome screen

---

src/main/java/edu/wpi/first/pathweaver/EditWaypointController.java
src/main/java/edu/wpi/first/pathweaver/MainController.java

Eliminates the save popup when a waypoint is selected but nothing changes

---

src/main/java/edu/wpi/first/pathweaver/Main.java

Force US locale

---

src/main/java/edu/wpi/first/pathweaver/global/DragHandler.java

Path Drag not working

---

src/main/java/edu/wpi/first/pathweaver/MainController.java
src/main/resources/edu/wpi/first/pathweaver/main.fxml

Autonomous Delete button can delete paths

---

src/main/java/edu/wpi/first/pathweaver/MainController.java

PathWeaver Locks-up When unsaved path is dragged to Path Group

---

src/main/java/edu/wpi/first/pathweaver/ProgramPreferences.java
src/main/java/edu/wpi/first/pathweaver/ProjectPreferences.java

From https://stackoverflow.com/questions/28937392/javafx-alerts-and-their-size
Supercedes #239
Fixes #181

Set alert dialogs to resize based on text

---

.github/workflows/main.yml

Update checkout, setup-java, upload download actions

---

dependencies.gradle

Also bump jackson to 2.12.4 to match allwpilib.

Update to 2024 dependencies

---

dependencies.gradle

Add quickbuf-runtime dependency

---

.github/workflows/main.yml
README.md

Needed to work with 2025 WPILib

Use JDK 17 and update readme

---

.github/workflows/main.yml

[ci] update actions for node 20

---

src/main/java/edu/wpi/first/pathweaver/Game.java
src/main/java/edu/wpi/first/pathweaver/extensions/ExtensionLoader.java

Moved in wpilibsuite/allwpilib#6694

Update fields location

---

build.gradle

Fixes running on macOS
Fixes #311

Update Tools and versioning plugin

---

src/main/java/edu/wpi/first/pathweaver/ProjectPreferences.java

Fix finding deploy directory when outputdir blank

---

src/main/java/edu/wpi/first/pathweaver/PathWeaver.java

Depends on wpilibsuite/frc-docs#2855 for the doc page.

Deprecate PathWeaver
